name: Build and push docker image

on:
    workflow_dispatch
    # push:
    #     tags: 
    #     - 'v*.*.*'

jobs:
  Build_and_push:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run : |
          IMAGE_TAG: ${{ github.ref_name }}
          docker build -t al0314/flask-docker-starterkit:$IMAGE_TAG .
      - name: Push docker images into hub
        run: |
          docker push al0314/flask-docker-starterkit:$IMAGE_TAG  
